### ISSUE TITLE
Feature request: Multivalue path

### ISSUE THREAD

**Issue by apetryla** [stacscan/stacs#18]
Would it be possible to implement a multiple path feature, which might look like this:
`stacs --rule-pack rules.json my_file_1 my_file_2 ...`

This would reduce the boilerplate code and necessity to write:
```
stacs --rule-pack rules.json my_file_1
stacs --rule-pack rules.json my_file_2
...
```
Maybe this could be a possible implementation:
`@click.argument('path', type=str, nargs=-1)`
Another implementation idea can be a path of the form _"my_file_1,my_file_2,..."_ and then parsed like
`path.split(',')`
to have a list of paths. Then loop.

**Comment by darkarnium** [comment]
Hey there,

Thanks for the report, and the suggestion! I agree that I don't think this should be too difficult to add. Let me get this scheduled for the next release :)

**Comment by darkarnium** [comment]
Hey there 👋 

First pass at this is currently present in the v0.4.6 branch. In line with your suggestion, the "PATH" parameter now supports multiple paths. When specified files will be enumerated across all provided paths, and then the files scanned:

```
$ stacs --rule-pack ../stacs-rules/credential.json ../example ../another
2022-04-08 22:07:07,937 - 20210 - [INFO] STACS running with 10 threads
2022-04-08 22:07:07,937 - 20210 - [INFO] Attempting to load rule pack from ../stacs-rules/credential.json
2022-04-08 22:07:07,937 - 20210 - [INFO] Using cache directory at /tmp/1649452027937509
2022-04-08 22:07:07,937 - 20210 - [INFO] Attempting to get a list of files to scan from /.../example
2022-04-08 22:07:18,658 - 20210 - [INFO] Attempting to get a list of files to scan from /.../another
2022-04-08 22:07:18,662 - 20210 - [INFO] Found 7060 files for analysis
```

Sorry for the delay in getting to this one! This feature should be part of the 0.4.6 release, which I hope to have out in the next week.

**Comment by apetryla** [comment]
Looks good. Thank You for the effort. 

Note: I'll be out 'till Easter, so I won't be able to respond next week.

**Comment by darkarnium** [comment]
Hey there,

This has just been released! If you'd like to give it a try when you're able and let us know what you think that'd be greatly appreciated! :)

**Comment by apetryla** [comment]
I've tested it and it seems to work as expected. Thank You for this improvement! :)

**Comment by darkarnium** [comment]
No bother at all, thanks for the suggestion!
