### ISSUE TITLE
Proposal: non-0 exit-status when matches are found

### ISSUE THREAD

**Issue by apetryla** [stacscan/stacs#19]
I propose stacs to return non 0 exit status if at least 1 match (findings) with a rule is found.

The motivation for this is that in order to include stacs in automated pipeline, we need a switch (bool), which tells if stacs passes or fails. As such switch exit code is widely used in other python tools ([flake8](https://github.com/PyCQA/flake8), [mypy](https://github.com/python/mypy), [black](https://github.com/psf/black)). In addition, tools like [tox](https://pypi.org/project/tox/) provide pass/fail checking by the exit code.

If for some reason having this by default in stacs is not acceptable, I'd ask to have at least an option flag (for example, --fail-on-match), because otherwise I see no other way of including stacs into automated pipeline, but writing another piece of code, which parses stacs's logs, which would be an overhead.

**Comment by darkarnium** [comment]
Hey there,

Thanks for the suggestion! I agree that this would be useful, it should also simplify[ the logic which is currently implemented in stacs-ci](https://github.com/stacscan/stacs-ci/blob/37dfcf7f8efaaf524e608a9713aace1a4cd45cb5/wrapper/stacs-ci#L70.) today to detect and raise non-zero status on findings.

This functionality is definitely better placed inside of STACS, so I'll ensure that this is part of the upcoming v0.4.6 release.

**Comment by darkarnium** [comment]
Hey there 👋 

First pass at this is currently present in the v0.4.6 branch. In the upcoming release, findings will now trigger STACS to exit with a status of `100` if there are unsuppressed findings. This will be the default.

```
# 17 findings, 100 exit.
$ stacs --rule-pack ../stacs-rules/credential.json ../example
...
2022-04-08 22:07:18,662 - 20210 - [INFO] Found 7060 files for analysis
2022-04-08 22:08:10,692 - 20340 - [INFO] Generating SARIF from findings
2022-04-08 22:08:10,783 - 20340 - [INFO] Found 17 findings

$ echo $?
100

# 0 findings, 0 exit.
$ stacs --rule-pack ../stacs-rules/credential.json ../another
...
2022-04-08 22:12:54,128 - 20585 - [INFO] Found 9 files for analysis
2022-04-08 22:12:54,136 - 20585 - [INFO] Generating SARIF from findings
2022-04-08 22:12:54,136 - 20585 - [INFO] Found 0 findings
{"version": "2.1.0", ... }

$ echo $?
0
```

This feature should be part of the 0.4.6 release, which I hope to have out in the next week.

**Comment by apetryla** [comment]
Looks awesome. I'm looking forward. Thank You!

**Comment by darkarnium** [comment]
Hey there,

This has just been released! If you'd like to give it a try when you're able and let us know what you think that'd be greatly appreciated! :)

**Comment by apetryla** [comment]
I've tested it and it seems to work as expected. Thank You for this improvement! :)

**Comment by darkarnium** [comment]
No bother at all, thanks for the suggestion!

- Peter
