### ISSUE TITLE
Colorama dependency

### ISSUE THREAD

**Issue by m-1-k-3** [stacscan/stacs#32]
Hi Peter,

 during checking the pip dependencies of EMBA on the new Kali Linux I found a conflicting dependency on colorama:

```
Warning!!! Possibly conflicting dependencies found:
* stacs==0.4.14
 - colorama [required: ==0.4.5, installed: 0.4.6]
```

Would it be possible to update the colorama dependency to 0.4.6 or is there a reason to stick on 0.4.5?

Best
Mike

**Comment by darkarnium** [comment]
Hey @m-1-k-3 ,

Good catch! I'll relax these pins to allow updates within the same major version for all dependencies. This should be published as part of 0.4.15 shortly.

**Comment by m-1-k-3** [comment]
Thank you very much ...

**Comment by darkarnium** [comment]
Release has been tagged, build should be available on PyPi within the next 30 minutes :) 

https://github.com/stacscan/stacs/releases/tag/0.4.15

Thanks again for the report!
